CREATE DATABASE blog_db

CREATE TABLE users(
    IDUser INT PRIMARY KEY AUTO_INCREMENT,
    userName VARCHAR(50) NOT NULL,
    userLastName VARCHAR(50) NOT NULL,
    userGender CHAR(1) NOT NULL,
    userEmail VARCHAR(225) NOT NULL,
    userPassword VARCHAR(255) NOT NULL,
    userPhoto TEXT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE posts(
    IDPost INT PRIMARY KEY AUTO_INCREMENT,
    IDUser INT NOT NULL,
    postTitle VARCHAR(30) NOT NULL,
    postDescription LONGTEXT NOT NULL,
    postImage TEXT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (IDUser) REFERENCES users(IDUser)
);